version: 0.2

phases:
  pre_build:
    commands:
      - "echo 'Starting pre_build phase...'"
      - "aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"
      - "echo 'ECR Login command executed.'"
      - "REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPOSITORY_NAME"
      - "IMAGE_URI=$REPOSITORY_URI:latest"
      - "echo 'Pre_build phase completed.'"

  build:
    commands:
      - "echo 'Starting build phase...'"
      - "docker build -t $IMAGE_URI ."
      - "echo 'Docker image built.'"
      - "echo 'Build phase completed.'"

  post_build:
    commands:
      - "echo 'Starting post_build phase...'"
      - "docker push $IMAGE_URI"
      - "echo 'Docker image pushed to ECR.'"
      - "echo 'Image URI: $IMAGE_URI'"
      - "echo 'Post_build phase completed.'"
artifacts:
  files:
    - appspec.yml
    - scripts/**/*
